server:
  port: 8762

spring:
  main:
    web-application-type: reactive
#    allow-bean-definition-overriding: true

  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:9196
#  logstash:
#    server: logstash
#    port: 5000
#  zipkin:
#    base-url: ${ZIPKIN_URL:http://zipkin:9411}/
  cloud:
    gateway:
      routes:
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store/**
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - name: CircuitBreaker
              args:
                name: account-service
                fallbackuri: forward:/accountFallback
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallback
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productFallback
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
#
#  metrics:
#    distribution:
#      percentiles-histogram.http.server.requests: false
#      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
#      sla.http.server.requests: 500ms, 2000ms

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #60000

