server:
  port: ${PORT:8761}

spring:
  application:
    name: DISCOVERY-SERVICE

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

#spring:
#  devtools:
#    add-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "*"