server:
  port: ${PORT:2223}
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
#  logging:
#    pattern:
#      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#    level:
#      org.springframework: WARN
#      org.hibernate: WARN
#  logstash:
#    server: logstash
#    port: 5000
#  zipkin:
#    base-url: ${ZIPKIN_URL:http://zipkin:9411}/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#  metrics:
#    distribution:
#      percentiles-histogram.http.server.requests: false
#      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
#      sla.http.server.requests: 500ms, 2000ms
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.use-new-id-generator-mappings: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${db.host:localhost}:${db.port:3306}/store_ms_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
    username: root
    password: adminadmin
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    initialize: false
#    initialSize: 0
#    timeBetweenEvictionRunsMillis: 5000
#    minEvictableIdleTimeMillis: 5000
#    minIdle: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${DISCOVER_URL:http://discovery:8761}/eureka/

ribbon:
  eureka:
    enabled: false