server:
  port: ${PORT:2225}
  servlet:
    context-path: /account

spring:
  application:
    name: account-service
  config:
    import: configserver:http://localhost:9196

logging:
  pattern:
    file: /users/avishwaka1/sdsu-projects/sdsu-project/microservices-monitoring/logs/micro-account-service.log

#  zipkin:
#    base-url: ${ZIPKIN_URL:http://zipkin:9411}/


#  metrics:
#    distribution:
#      percentiles-histogram.http.server.requests: false
#      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
#      sla.http.server.requests: 500ms, 2000ms

ribbon:
  eureka:
    enabled: false